cloudmonkey/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogger/', include('blogger.urls')),
    path('college/', include('college.urls')),
    path('school/', include('school.urls')),

]

college/urls.py
from django.urls import path

from . import views

app_name = 'college'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/course/', views.CourseView.as_view(), name='course'),
    path('<int:pk>/department/', views.DepartmentView.as_view(), name='department'),
    path('<int:pk>/year/', views.SemesterView.as_view(), name='year'),
    path('<int:pk>/subject/', views.SubjectView.as_view(), name='subject'),
    path('add/', views.CollegeCreate.as_view(), name='college_add'),
    path('add_course/', views.CourseCreate.as_view(), name='course_add'),
    path('add_department/', views.DepartmentCreate.as_view(), name='department_add'),
    path('add_semester/', views.SemesterCreate.as_view(), name='semester_add'),

    ]

school/urls.py
from django.urls import path

from . import views

app_name = 'school'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/class/', views.IndexView.as_view(), name='class'),
    path('<int:pk>/subject/', views.IndexView.as_view(), name='subject'),

    path('add/', views.SchoolCreate.as_view(), name='school_add'),
    ]

college/models.py
from django.db import models
from django.utils.timezone import now
from django.urls import reverse

# Create your models here.


class College(models.Model):
    name = models.CharField(max_length=50)
    college_logo=models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=now)
    address=models.CharField(max_length=100)
    city= models.CharField(max_length=50)
    country=models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('college:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name +'-' +self.address +'-'+ self.city


class Department(models.Model):
    College = models.ForeignKey(College, on_delete=models.CASCADE,)
    department_name = models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)

    def get_absolute_url(self):
        return reverse('college:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.department_name

class Course(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE,)
    course_name=models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)

    def get_absolute_url(self):
        return reverse('college:department', kwargs={'pk': self.pk})

    def __str__(self):
        return self.course_name


class Semester(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    semester_name = models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)

    def get_absolute_url(self):
        return reverse('college:course', kwargs={'pk': self.pk})

    def __str__(self):
        return self.semester_name


class Subject(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    subject_name = models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)

    def get_absolute_url(self):
        return reverse('college:semester', kwargs={'pk': self.pk})

    def __str__(self):
        return self.subject_name


class Type(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    type = models.CharField(max_length=51)
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)
    note=models.FileField()

college/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView

from .models import *


class IndexView(generic.ListView):
    template_name = 'college/index.html'
    context_object_name = 'college'

    def get_queryset(self):
        """Return the last five published questions."""
        return College.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = College
    template_name = 'college/detail.html'

class DepartmentView(generic.DetailView):
    model = Department
    template_name = 'college/department.html'


class CourseView(generic.DetailView):
    model = Course
    template_name = 'college/course.html'

class SemesterView(generic.DetailView):
    model = Semester
    template_name = 'college/year.html'

class SubjectView(generic.DetailView):
    model = Subject
    template_name = 'college/subject.html'

class CollegeCreate(CreateView):
    model = College
    fields = ['name','college_logo','address','city','country']


class DepartmentCreate(CreateView):
    model = Department
    fields = ['College','department_name']



class CourseCreate(CreateView):
    model = Course
    fields = ['department','course_name']

class SemesterCreate(CreateView):
    model = Semester
    fields = ['course','semester_name']

college/templates/college/college_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>form</title>
</head>
<body>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}


    {{ form.as_p }}

    <button type="submit">submit</button>

    </form>

</body>
</html>

college/templates/college/course.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>course</title>
</head>
<body>

<h1>{{ course.course_name }}</h1>
{% if course.semester_set.all %}
    <ul>
    {% for semester in course.semester_set.all %}
        <li><a href="{% url 'college:subject' %}">{{semester.semester_name}}</a></li>
    {% endfor %}
    </ul>
{% else%}

   no semester are available

{% endif %}

<a href="{% url 'college:semester_add'%}">add semester</a>

</body>
</html>

college/templates/college/course_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>course form</title>
</head>
<body>
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}


    {{ form.as_p }}

    <button type="submit">submit</button>

    </form>

</body>
</html>

college/templates/college/department.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>department</title>
</head>
<body>

{% if department.course_set.all %}

    <ul>
    {% for course in department.course_set.all %}
        <li><a href=" {% url 'college:course'  course.id  %} "> {{course.course_name}}</a></li>
    {% endfor %}
    </ul>

{% else %}
    no course available

{% endif%}

<a href="{% url 'college:course_add'%}">add course</a>

</body>
</html>

college/templates/college/department_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}


    {{ form.as_p }}

    <button type="submit">submit</button>

    </form>

</body>
</html>

college/templates/college/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>

{{ college.name }}
<img src="{{ college.college_logo }}" >
{{ college.address }}
{{ college.city }}
{{ college.country }}

<br>

{% if college.department_set.all %}

    <ul>
    {% for department in college.department_set.all %}
        <li><a href=" {% url 'college:department'  department.id  %} "> {{department.department_name}}</a></li>
    {% endfor %}
    </ul>

{% else %}
    no department available

{% endif%}

<a href="{% url 'college:department_add'%}">add department</a>



</body>
</html>

college/templates/college/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index college</title>
</head>
<body>
{% if college %}
    <ul>
    {% for college in college %}
        <li><a href="{% url 'college:detail' college.id %}">{{ college.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No college are available.</p>
{% endif %}

<a href="{% url 'college:college_add' %}">add</a>

</body>
</html>

college/templates/college/semester_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>semester</title>
</head>
<body>
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}


    {{ form.as_p }}

    <button type="submit">submit</button>

    </form>

</body>
</html>

college/templates/college/subject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>subjects</title>
</head>
<body>

hi

</body>
</html>