cloudmonkey/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogger/', include('blogger.urls')),
    path('college/', include('college.urls')),
    path('school/', include('school.urls')),

]

school/urls.py
from django.urls import path

from . import views

app_name = 'school'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/class/', views.IndexView.as_view(), name='class'),
    path('<int:pk>/subject/', views.IndexView.as_view(), name='subject'),

    path('add/', views.SchoolCreate.as_view(), name='school_add'),
    ]

school/models.py
from django.db import models
from django.utils.timezone import now
from django.urls import reverse


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=50)
    school_logo= models.CharField(max_length=500)
    pub_date = models.DateTimeField(default=now)
    address=models.CharField(max_length=100)
    city= models.CharField(max_length=50)
    country=models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('school:detail', kwargs={'pk': self.pk})


    def __str__(self):
        return self.name +'-' +self.address +'-'+ self.city


class Board(models.Model):
    board_name=models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)


class Class(models.Model):
    course = models.ForeignKey(Board, on_delete=models.CASCADE)
    class_name=models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)



class Subject(models.Model):
    department = models.ForeignKey(Class, on_delete=models.CASCADE)
    sub_name = models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)


class Type(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    type = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    pub_date = models.DateTimeField(default=now)
    note = models.FileField()

school/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import *


class IndexView(generic.ListView):
    template_name = 'school/index.html'
    context_object_name = 'school'

    def get_queryset(self):
        """Return the last five published questions."""
        return School.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = School
    template_name = 'school/detail.html'


class ClassView(generic.DetailView):
    model = Class
    template_name = 'school/class.html'


class SubjectView(generic.DetailView):
    model = Subject
    template_name = 'school/subject.html'


class SchoolCreate(CreateView):
    model = School
    fields = ['name','school_logo','address','city','country']

school/templates/school/class.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>class</title>
</head>
<body>
school_class
</body>
</html>

school/templates/school/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>detail</title>
</head>
<body>
{{ school.name }}
<img src="{{ school.school_logo }}" >
{{ school.address }}
{{ school.city }}
{{ school.country }}




</body>
</html>

school/templates/school/form_template.html
{% for field in form %}
<span>{{field.errors}}</span>
<label>field.label_tag</label>
{{field}}

{% endfor %}

school/templates/school/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
</head>
<body>
school_index

{% if school %}
    <ul>
    {% for school in school %}
        <li><a href="{% url 'school:detail' school.id %}">{{ school.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No schools are available.</p>
{% endif %}

<a href="{% url 'school:school_add' %}">add</a>
</body>
</html>

school/templates/school/school_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>form</title>
</head>
<body>
<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}


    {{ form.as_p }}

    <button type="submit">submit</button>

    </form>

</body>
</html>

school/templates/school/subject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>subject</title>
</head>
<body>
school_subject
</body>
</html>